### ISSUE TITLE
Process path is empty

### ISSUE THREAD

**Issue by pieterdegraeuwe** [ITachiLab/hotkey-detective#19]
I noticed since a few days that some shortcuts(kotkeus) in min IDE (IntelliJ IDEA) are not working anymore.
I came across this tool. 

It seems indeed to detect some shortcuts. However. Some aren't. (the ones dat are working in my IDE).
The ones that aren't working in my IDE, are detected by hotkey-detective, but the path is empty. (see screenshot CTRL+ALT+L)
![image](https://github.com/ITachiLab/hotkey-detective/assets/1360039/7feb25f5-3979-4692-8d16-76bf62d7d82d)
Any ideas how I can find out what is causing this?

Thanks!

**Comment by mustafadakhel** [comment]
i am currently facing the exact same problem (been facing it for the past week), same shortcut and same ide, and after trying this tool, the path is empty, so i am currently unable to reformat my code since this shortcut is used for that purpose in the ide, did you find any solution for it?

**Comment by mustafadakhel** [comment]
@pieterdegraeuwe it was Asus Armory Crate for me, they released an update that captures the CTRL ALT L  shortcut at all times without notice, if you're using an asus too, you can change it by going to devices->your device->resource monitor->enable real-time monitor on the right side panel, and click the button to change its settings, dont forget to disable it again, although even when its disabled its still capturing the shortcuts

**Comment by jlhervy** [comment]
> @pieterdegraeuwe it was Asus Armory Crate for me, they released an update that captures the CTRL ALT L shortcut at all times without notice, if you're using an asus too, you can change it by going to armory crate->devices->your device->resource monitor->enable real-time monitor on the right side panel, and click the button to change its settings, dont forget to disable it again, although even when its disabled its still capturing the shortcuts

Thanks a lot !!! I was searching why CTRL ALT L would not work anymore in jetbrains' IDE / VS Code

**Comment by pieterdegraeuwe** [comment]
> @pieterdegraeuwe it was Asus Armory Crate for me, they released an update that captures the CTRL ALT L shortcut at all times without notice, if you're using an asus too, you can change it by going to armory crate->devices->your device->resource monitor->enable real-time monitor on the right side panel, and click the button to change its settings, dont forget to disable it again, although even when its disabled its still capturing the shortcuts

Correct, also using Asus here.  Changing those hotkey's to something else solves the problem. Pitty you can't just remove the hotkey completely.
Anyway. 
Problem solved. Thanks!
